project_id = "ajccptfvmfbkpriblahh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "600MiB"
bucket_defaults = { public = false }

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ajccptfvmfbkpriblahh.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[functions.admin-auth]
verify_jwt = false

[functions.content-upload]
verify_jwt = false

[functions.ai-moderator]
verify_jwt = false

[functions.process-content]
verify_jwt = false

[functions.get-queue]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.cleanup-expired-content]
verify_jwt = false

[functions.generate-playlist]
verify_jwt = false

[functions.report-play]
verify_jwt = false

[functions.clean-storage-bucket]
verify_jwt = false