// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajccptfvmfbkpriblahh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqY2NwdGZ2bWZia3ByaWJsYWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NzQ0MDcsImV4cCI6MjA3NDE1MDQwN30.duzucdb3lF4FcGJ7ozsEwpNaImQBR90Vslvr-gJ5rAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});